name: 7z release test


on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: edgarrc/action-7z@v1
      with:
        args: 7z a -t7z -mx=9 build.7z ./Bfruit (PyGame)/
