name: 7z release test


on:
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install 7zip
        run: sudo apt-get -y install p7zip-full

      - name: Zip Directories and Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0 # Remplacez par la tag name pour la nouvelle release
          release_name: Release v1.0.0 # Remplacez par le nom pour la nouvelle release
          body: Release Notes # Remplacez par la description pour la nouvelle release
          draft: false
          prerelease: false

      - name: Zip Directories and Upload to Release
        id: upload_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for dir in */; do
            7z a -tzip $dir.zip $dir && echo $dir.zip && \
            curl --data-binary "@$dir.zip" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" -X POST "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=${dir::-1}.zip" && \
            rm $dir.zip
          done