name: Generate Image Table

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate Image Table
        run: |
          echo "|Name|Size|"
          echo "|----|----|"
          find . -type d -name "Imgs" -print0 | while read -d $'\0' dir; do
            name=$(basename $(dirname "$dir"))
            echo "|$name| |"
            for image in $(find "$dir" -type f -name "*.png"); do
              image_name=$(basename "$image")
              image_size=$(curl --silent --head "https://api.github.com/repos/${{ github.repository }}/releases/assets/${{ env.ASSET_ID }}" | grep -i "^content-length:" | sed -e 's/^[Cc]ontent-[Ll]ength:[[:space:]]*//')
              printf "|<a href=\"https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/$name/$image_name\"><img src=\"$image\" alt=\"$name\" height=\"200\" /></a>|$((image_size/1024)) kB|\n"
            done
          done > Table.md

      - name: Commit table to repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Table.md
          git commit -m "Generate image table"
          git push
