name: Generate a table of PNG images in directories

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create table of images
      run: |
        echo "| Directory | Image | Size |" > Table.md
        echo "| :--------: | :---: | :--: |" >> Table.md
        for dir in $(find . -type d -print); do
          if [ -d "$dir/Roms/PORTS/Imgs" ]; then
            image=$(find "$dir/Roms/PORTS/Imgs" -maxdepth 1 -type f -name "*.png")
            if [ -n "$image" ]; then
              name=$(basename "$dir")
              release=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | jq -r '.assets[] | select(.name | contains("'"$name"'")) | .browser_download_url')
              size=$(curl --head --silent "$release" | grep -i content-length | awk '{print $2}' | numfmt --to=iec)
              echo "| [$name]($release) | <a href=\"$release\"><img src=\"$image\" alt=\"$name\" height=\"200\" /></a> | $size |" >> Table.md
            fi
          fi
        done
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Table.md
        git commit -m "Add table of PNG images in directories"
        git push
