name: Generate a table of PNG images in directories

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create table of images
      run: |
        echo "| Directory | File | Image | Size | Modified |" > Table.md
        echo "| :--------: | :--: | :---: | :--: | :------: |" >> Table.md
        for dir in $(find . -type d -print); do
          if [ -d "$dir/Roms/PORTS/Imgs" ]; then
            image=$(find "$dir/Roms/PORTS/Imgs" -maxdepth 1 -type f -name "*.png")
            if [ -n "$image" ]; then
              name=$(basename "$dir")
              release=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | jq -r '.assets[] | select(.name | contains("'"$name"'")) | .browser_download_url')
              size=$(du -h "$image" | awk '{print $1}')
              modified=$(date -r "$image" "+%Y-%m-%d %H:%M:%S")
              echo "| [$name]($release) | [$image]($image) | <img src=\"$image\" alt=\"$name\" height=\"200\" /> | $size | $modified |" >> Table.md
            fi
          fi
        done
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Table.md
        git commit -m "Add table of PNG images in directories"
        git push